services:
  coordinator:
    build:
      context: ../..
      dockerfile: examples/nyc-taxi/Dockerfile
    environment:
      ROLE: coordinator
      NODE_ID: "1"
      PORT: "5000"
      WORKER_ADDRS: "worker-2:5000,worker-3:5000,worker-4:5000,worker-5:5000"
    ports:
      - "5000:5000"
    networks:
      - ironpipe
    depends_on:
      - worker-2
      - worker-3
      - worker-4
      - worker-5

  worker-2:
    build:
      context: ../..
      dockerfile: examples/nyc-taxi/Dockerfile
    environment:
      ROLE: worker
      NODE_ID: "2"
      PORT: "5000"
      COORDINATOR_ADDR: "coordinator:5000"
    networks:
      - ironpipe

  worker-3:
    build:
      context: ../..
      dockerfile: examples/nyc-taxi/Dockerfile
    environment:
      ROLE: worker
      NODE_ID: "3"
      PORT: "5000"
      COORDINATOR_ADDR: "coordinator:5000"
    networks:
      - ironpipe

  worker-4:
    build:
      context: ../..
      dockerfile: examples/nyc-taxi/Dockerfile
    environment:
      ROLE: worker
      NODE_ID: "4"
      PORT: "5000"
      COORDINATOR_ADDR: "coordinator:5000"
    networks:
      - ironpipe

  worker-5:
    build:
      context: ../..
      dockerfile: examples/nyc-taxi/Dockerfile
    environment:
      ROLE: worker
      NODE_ID: "5"
      PORT: "5000"
      COORDINATOR_ADDR: "coordinator:5000"
    networks:
      - ironpipe

networks:
  ironpipe:
    driver: bridge
